# Clear a part of the map, specified by a bounding volume. 
# Sets all voxels inside the bounding volume to ~clamping_thres_min/free space.

# The bounding volume
ufomap_msgs/BoundingVolume bounding_volume
# The depth at which it should be cleared
uint8 depth
---
# If it was successful
bool success
