# Get the complete map at a specified depth

# The depth of the map to return
uint8 depth
# If the message should be compressed
bool compress
# Bounding volume of which part of the map should be returned
ufomap_msgs/BoundingVolume bounding_volume
---
# If it was successful
bool success
# The map to be returned
ufomap_msgs/UFOMap map
