# Save the map to file

# Name of the file
string filename
# The depth of the map to save
uint8 depth
# If the file should be compressed
bool compress
# Bounding volume of which part of the map should be saved
ufomap_msgs/BoundingVolume bounding_volume
---
# If it was successful
bool success
